name: Update README.md

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # install the python version needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update README.md
        run: |
          python feed.py

      - name: Commit README.md
        run: |
          timestamp=$(date -u)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Automated update: ${timestamp} ${GITHUB_SHA}" || echo "No changes to commit"

      - name: Push README.md
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
